/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ImprovedUiRouteImport } from './routes/improved-ui'
import { Route as IndexRouteImport } from './routes/index'

const ImprovedUiRoute = ImprovedUiRouteImport.update({
  id: '/improved-ui',
  path: '/improved-ui',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/improved-ui': typeof ImprovedUiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/improved-ui': typeof ImprovedUiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/improved-ui': typeof ImprovedUiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/improved-ui'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/improved-ui'
  id: '__root__' | '/' | '/improved-ui'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ImprovedUiRoute: typeof ImprovedUiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/improved-ui': {
      id: '/improved-ui'
      path: '/improved-ui'
      fullPath: '/improved-ui'
      preLoaderRoute: typeof ImprovedUiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ImprovedUiRoute: ImprovedUiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
